### ISSUE TITLE
Thanks, I'll link to this from the TS site!

### ISSUE THREAD

**Issue by JdeH** [fzzylogic/phaser3_transcrypt_tutorial#1]

**Comment by fzzylogic** [comment]
@JdeH Thanks, hopefully more interesting examples will be available in future..

**Comment by JdeH** [comment]
I've tried to avoid the "this", but that requires delving into Phaser3 and JS misty "this" magic. On top of that it would suggest that one has to do something "difficult" to use Transcrypt. What I like about this example is that it shows how straightforward conversion can be, so I consider it useful in its own right.

There's always an "interface surface" with the JS lib in question, which, by nature of JS, can be a little bit ugly. But apart from that interface, a clean Pythonic overall structure can be drawn up for game logic, dynamics etc..

Defining the right API with a JS lib is an art. In this case it is thin, or even absent, which is a defendable choice for a simple one-off. The other extreme is extensive use of design patterns like Facade and Bridge, overkill in many cases, but maybe worthwhile if a JS lib is to be used extensively.
